// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl3SbauHcgslIwDuch-b_QtYRoVcC7oOs',
    appId: '1:837914510150:web:3bee7a3b72f527c2ca9b47',
    messagingSenderId: '837914510150',
    projectId: 'lost-and-found-3d66f',
    authDomain: 'lost-and-found-3d66f.firebaseapp.com',
    storageBucket: 'lost-and-found-3d66f.appspot.com',
    measurementId: 'G-QE5S56XYFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD9berda2SbbXACr883zMJlpJ9EA2xZa4',
    appId: '1:837914510150:android:07fd4de5f28f96d8ca9b47',
    messagingSenderId: '837914510150',
    projectId: 'lost-and-found-3d66f',
    storageBucket: 'lost-and-found-3d66f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuZuYXZxYOso7qSWg5VAs728saHMjJM8',
    appId: '1:837914510150:ios:51c517318867bf18ca9b47',
    messagingSenderId: '837914510150',
    projectId: 'lost-and-found-3d66f',
    storageBucket: 'lost-and-found-3d66f.appspot.com',
    iosClientId: '837914510150-45i3am97jqib7reocsk8ecfki7sjd2oe.apps.googleusercontent.com',
    iosBundleId: 'com.sachitbansal.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALuZuYXZxYOso7qSWg5VAs728saHMjJM8',
    appId: '1:837914510150:ios:51c517318867bf18ca9b47',
    messagingSenderId: '837914510150',
    projectId: 'lost-and-found-3d66f',
    storageBucket: 'lost-and-found-3d66f.appspot.com',
    iosClientId: '837914510150-45i3am97jqib7reocsk8ecfki7sjd2oe.apps.googleusercontent.com',
    iosBundleId: 'com.sachitbansal.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl3SbauHcgslIwDuch-b_QtYRoVcC7oOs',
    appId: '1:837914510150:web:f1fe656549628071ca9b47',
    messagingSenderId: '837914510150',
    projectId: 'lost-and-found-3d66f',
    authDomain: 'lost-and-found-3d66f.firebaseapp.com',
    storageBucket: 'lost-and-found-3d66f.appspot.com',
    measurementId: 'G-Q6QR0M8VS3',
  );
}
